version: 0.0
os: linux
overwrite: true
files:
  - source: /
    destination: /home/ubuntu/opt/laravel/
 permissions:
  - object: /home/ubuntu/opt/laravel/
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: deploy/beforeinstall.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy/afterinstall.sh
      timeout: 300
      runas: ubuntu   
 


