version: 0.0
os: linux
overwrite: true
files:
  - source: /
    destination: /home/root/opt/laravel/
hooks:
  BeforeInstall:
    - location: deploy/beforeinstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/afterinstall.sh
      timeout: 300
      runas: root   
 


