
name: Upload Staging Branch Code to S3

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  

      - name: Build .zip archive
        run: |
          zip -r code_file.zip .
          echo "Successfully created code_file.zip"

      - name: Upload .zip to S3
        run: |
          aws s3 cp code_file.zip s3://demo-code-deploy190723/code_file.zip
          echo "Uploaded code_file.zip to S3 bucket"
          
          
      - name: Trigger the code-deploy service
        run: |
           aws deploy push --application-name Demoaddval-codedeploy --s3-location s3://demo-code-deploy190723/code_file.zip --region ap-south-1
           aws deploy create-deployment --application-name Demoaddval-codedeploy --s3-location bucket=demo-code-deploy190723,key=code_file.zip,bundleType=zip --deployment-group-name Demoaddval-codedeploy-group --deployment-config-name CodeDeployDefault.AllAtOnce
