
name: Upload Staging Branch Code to S3

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  

      - name: Build .zip archive
        run: |
          zip -r source_file.zip .
          echo "Successfully created source_file.zip"

      - name: Upload .zip to S3
        run: |
          aws s3 cp source_file.zip s3://demoaddval/source_file.zip
          echo "Uploaded source_file.zip to S3 bucket"
          
          
      - name: Trigger the code-deploy service
        run: |
           aws deploy push --application-name demoaddval --s3-location s3://demoaddval/source_file.zip --region ap-south-1
           aws deploy create-deployment --application-name demoaddval --s3-location bucket=demoaddval,key=source_file.zip,bundleType=zip --deployment-group-name demoaddval-group --deployment-config-name CodeDeployDefault.AllAtOnce
